# Generated by Django 4.2.7 on 2024-03-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PG',
            fields=[
                ('pg_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pg_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Status_PG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('total_strength', models.IntegerField()),
                ('vaccancies', models.IntegerField()),
                ('images', models.ImageField(upload_to='images/')),
                ('pg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.pg')),
            ],
        ),
    ]
