# Generated by Django 4.2.7 on 2024-03-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_PG',
            fields=[
                ('Registration_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Full_name', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=50)),
                ('Mobile_number', models.IntegerField()),
            ],
        ),
    ]
