# Generated by Django 4.2.7 on 2024-03-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_alter_registration_pg_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_pg',
            name='price_person',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registration_pg',
            name='sharing_person',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
